#!/bin/sh

echo '(1) date'
echo '(2) who'
echo '(3) pwd'
echo '(4) ls -l'
echo
echo -n '  input no:'
read no
echo
case $no in
	1) date
		;;
	2) who
		;;
	3) pwd
		;;
	4) ls -l
		;;
	*) echo 'Please input number'
		;;
esac
	
