#!/bin/sh

for i
do

if [ -f $i ]
	then echo $i >> Ofile
	elif [ -d $i ]
		then echo $i >> Dfile
	else echo ${i}はfileでもdirectoryでもない
fi

done

for f in Ofile Dfile
do
	if [ -s $f ]
		then echo "---${f}---"
			cat $f
	fi
done
