#!/bin/sh

echo '('1')'date
echo '('2')'who
echo '('3')'pwd
echo '('4')'ls -l 

echo -n input no:
read num


case $num in
	1) date
	;;
	2) who
	;;
	3) pwd
	;;
	4) ls -l
	;;
	*) echo 'Plese input number'
	;;
esac
